version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80" # You can set 3050 to whatever you want
  api:
    build:
      dockerfile: Dockerfile.dev # Just the name of the file - no need for path
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app # Any changes will be made on server folder will be reflected on app folder so we won't build the image every time
    environment:
      - REDIS_HOST=redis # # Same to service name or IP/Address if not int he same image
      - REDIS_PORT=6379 # Default Redis port
      - PGUSER=postgres
      - PGHOST=postgres # Same to service name
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password # Default Postgres password
      - PGPORT=5432 # Default Postgres port
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
